
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Domain','com_uforeporting.domain','{"special":{"dbtable":"#__ommp_domains","key":"id","type":"Domain","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/domain.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.domain')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Domain', 
	`table` = '{"special":{"dbtable":"#__ommp_domains","key":"id","type":"Domain","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/domain.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.domain');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Behavior','com_uforeporting.behavior','{"special":{"dbtable":"#__ommp_behaviors","key":"id","type":"Behavior","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/behavior.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.behavior')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Behavior', 
	`table` = '{"special":{"dbtable":"#__ommp_behaviors","key":"id","type":"Behavior","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/behavior.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.behavior');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Environment','com_uforeporting.environment','{"special":{"dbtable":"#__ommp_environment","key":"id","type":"Environment","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/environment.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.environment')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Environment', 
	`table` = '{"special":{"dbtable":"#__ommp_environment","key":"id","type":"Environment","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/environment.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.environment');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Kinematic','com_uforeporting.kinematic','{"special":{"dbtable":"#__ommp_observer_kinematics","key":"id","type":"Kinematic","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/kinematic.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.kinematic')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Kinematic', 
	`table` = '{"special":{"dbtable":"#__ommp_observer_kinematics","key":"id","type":"Kinematic","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/kinematic.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.kinematic');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Vehicle','com_uforeporting.vehicle','{"special":{"dbtable":"#__ommp_observer_vehicle","key":"id","type":"Vehicle","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/vehicle.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.vehicle')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Vehicle', 
	`table` = '{"special":{"dbtable":"#__ommp_observer_vehicle","key":"id","type":"Vehicle","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/vehicle.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.vehicle');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Pair','com_uforeporting.pair','{"special":{"dbtable":"#__ommp_invalid_pairs","key":"id","type":"Pair","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/pair.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.pair')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Pair', 
	`table` = '{"special":{"dbtable":"#__ommp_invalid_pairs","key":"id","type":"Pair","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/pair.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.pair');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Sighting','com_uforeporting.sighting','{"special":{"dbtable":"#__ommp_sightings","key":"id","type":"Sighting","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/sighting.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.sighting')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Sighting', 
	`table` = '{"special":{"dbtable":"#__ommp_sightings","key":"id","type":"Sighting","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/sighting.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.sighting');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Media','com_uforeporting.media','{"special":{"dbtable":"#__ommp_media","key":"id","type":"Media","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/media.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.media')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Media', 
	`table` = '{"special":{"dbtable":"#__ommp_media","key":"id","type":"Media","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/media.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.media');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Witnesse','com_uforeporting.witnesse','{"special":{"dbtable":"#__ommp_witnesses","key":"id","type":"Witnesse","prefix":"UforeportingTable"}}', '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/witnesse.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_uforeporting.witnesse')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Witnesse', 
	`table` = '{"special":{"dbtable":"#__ommp_witnesses","key":"id","type":"Witnesse","prefix":"UforeportingTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_uforeporting\/models\/forms\/witnesse.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_uforeporting.witnesse');
