CREATE TABLE IF NOT EXISTS `#__peerreview_articles` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(400) NOT NULL DEFAULT '',
    `abstract` text,
    `fulltext` mediumtext,
    `keywords` varchar(500) DEFAULT NULL,
    `doi` varchar(255) DEFAULT NULL,
    `author_id` int(10) unsigned NOT NULL DEFAULT 0,
    `category_id` int(10) unsigned NOT NULL DEFAULT 0,
    `status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '0=draft,1=submitted,2=under_review,3=revisions_required,4=accepted,5=published,6=rejected',
    `submission_date` datetime DEFAULT NULL,
    `acceptance_date` datetime DEFAULT NULL,
    `publication_date` datetime DEFAULT NULL,
    `version` int(10) unsigned NOT NULL DEFAULT 1,
    `downloads` int(10) unsigned NOT NULL DEFAULT 0,
    `views` int(10) unsigned NOT NULL DEFAULT 0,
    `metadata` json DEFAULT NULL,
    `ai_suggestions` json DEFAULT NULL,
    `published` tinyint(3) NOT NULL DEFAULT 0,
    `checked_out` int(10) unsigned DEFAULT NULL,
    `checked_out_time` datetime DEFAULT NULL,
    `created` datetime NOT NULL,
    `created_by` int(10) unsigned NOT NULL DEFAULT 0,
    `modified` datetime DEFAULT NULL,
    `modified_by` int(10) unsigned NOT NULL DEFAULT 0,
    `publish_up` datetime DEFAULT NULL,
    `publish_down` datetime DEFAULT NULL,
    `params` text,
    `language` char(7) NOT NULL DEFAULT '*',
    `ordering` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_status` (`status`),
    KEY `idx_category` (`category_id`),
    KEY `idx_author` (`author_id`),
    KEY `idx_published` (`published`),
    KEY `idx_alias` (`alias`(191)),
    KEY `idx_language` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__peerreview_reviews` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `article_id` int(10) unsigned NOT NULL,
    `reviewer_id` int(10) unsigned NOT NULL,
    `round` tinyint(3) unsigned NOT NULL DEFAULT 1,
    `recommendation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '0=pending,1=accept,2=minor_revisions,3=major_revisions,4=reject',
    `comments_to_author` mediumtext,
    `comments_to_editor` mediumtext,
    `technical_quality` tinyint(3) unsigned DEFAULT NULL,
    `originality` tinyint(3) unsigned DEFAULT NULL,
    `clarity` tinyint(3) unsigned DEFAULT NULL,
    `significance` tinyint(3) unsigned DEFAULT NULL,
    `ai_analysis` json DEFAULT NULL,
    `assigned_date` datetime NOT NULL,
    `due_date` datetime DEFAULT NULL,
    `submitted_date` datetime DEFAULT NULL,
    `status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '0=pending,1=in_progress,2=completed,3=declined',
    `published` tinyint(3) NOT NULL DEFAULT 1,
    `created` datetime NOT NULL,
    `created_by` int(10) unsigned NOT NULL DEFAULT 0,
    `modified` datetime DEFAULT NULL,
    `modified_by` int(10) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_article` (`article_id`),
    KEY `idx_reviewer` (`reviewer_id`),
    KEY `idx_status` (`status`),
    KEY `idx_round` (`round`),
    CONSTRAINT `fk_article_review` FOREIGN KEY (`article_id`) REFERENCES `#__peerreview_articles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__peerreview_reviewers` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `user_id` int(10) unsigned NOT NULL,
    `expertise` varchar(500) DEFAULT NULL,
    `affiliation` varchar(255) DEFAULT NULL,
    `orcid` varchar(19) DEFAULT NULL,
    `bio` text,
    `h_index` int(10) unsigned DEFAULT NULL,
    `total_reviews` int(10) unsigned NOT NULL DEFAULT 0,
    `completed_reviews` int(10) unsigned NOT NULL DEFAULT 0,
    `average_rating` decimal(3,2) DEFAULT NULL,
    `response_time_avg` int(10) unsigned DEFAULT NULL COMMENT 'Average response time in days',
    `availability` tinyint(3) NOT NULL DEFAULT 1,
    `max_concurrent_reviews` tinyint(3) unsigned NOT NULL DEFAULT 3,
    `preferences` json DEFAULT NULL,
    `published` tinyint(3) NOT NULL DEFAULT 1,
    `created` datetime NOT NULL,
    `created_by` int(10) unsigned NOT NULL DEFAULT 0,
    `modified` datetime DEFAULT NULL,
    `modified_by` int(10) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_user` (`user_id`),
    KEY `idx_availability` (`availability`),
    KEY `idx_expertise` (`expertise`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__peerreview_categories` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `parent_id` int(10) unsigned NOT NULL DEFAULT 0,
    `lft` int(11) NOT NULL DEFAULT 0,
    `rgt` int(11) NOT NULL DEFAULT 0,
    `level` int(10) unsigned NOT NULL DEFAULT 0,
    `path` varchar(400) NOT NULL DEFAULT '',
    `title` varchar(255) NOT NULL,
    `alias` varchar(400) NOT NULL DEFAULT '',
    `description` text,
    `published` tinyint(3) NOT NULL DEFAULT 1,
    `checked_out` int(10) unsigned DEFAULT NULL,
    `checked_out_time` datetime DEFAULT NULL,
    `access` int(10) unsigned NOT NULL DEFAULT 0,
    `params` text,
    `language` char(7) NOT NULL DEFAULT '*',
    `created` datetime NOT NULL,
    `created_by` int(10) unsigned NOT NULL DEFAULT 0,
    `modified` datetime DEFAULT NULL,
    `modified_by` int(10) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_alias` (`alias`(191)),
    KEY `idx_path` (`path`(191)),
    KEY `idx_left_right` (`lft`,`rgt`),
    KEY `idx_language` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__peerreview_coauthors` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `article_id` int(10) unsigned NOT NULL,
    `name` varchar(255) NOT NULL,
    `email` varchar(255) DEFAULT NULL,
    `affiliation` varchar(255) DEFAULT NULL,
    `orcid` varchar(19) DEFAULT NULL,
    `ordering` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_article` (`article_id`),
    CONSTRAINT `fk_article_coauthor` FOREIGN KEY (`article_id`) REFERENCES `#__peerreview_articles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__peerreview_files` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `article_id` int(10) unsigned NOT NULL,
    `filename` varchar(255) NOT NULL,
    `original_name` varchar(255) NOT NULL,
    `file_type` varchar(50) NOT NULL,
    `file_size` int(10) unsigned NOT NULL,
    `file_path` varchar(500) NOT NULL,
    `purpose` varchar(50) NOT NULL DEFAULT 'manuscript' COMMENT 'manuscript,supplement,figure,data',
    `version` int(10) unsigned NOT NULL DEFAULT 1,
    `uploaded` datetime NOT NULL,
    `uploaded_by` int(10) unsigned NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_article` (`article_id`),
    KEY `idx_purpose` (`purpose`),
    CONSTRAINT `fk_article_file` FOREIGN KEY (`article_id`) REFERENCES `#__peerreview_articles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

-- Insert root category
INSERT INTO `#__peerreview_categories` (`id`, `parent_id`, `lft`, `rgt`, `level`, `path`, `title`, `alias`, `published`, `access`, `language`, `created`, `created_by`) 
VALUES (1, 0, 0, 1, 0, '', 'ROOT', 'root', 1, 1, '*', NOW(), 0);